HOST_IP = "localhost"
USER = "root"
PASSWORD = "123456789"
GROUP_NAME = "GroupA"
DEVICE_ID = "DeviceA"

MQTT_HOSTNAME = "nam1.cloud.thethings.network"
MQTT_USERNAME = "4id3-data-collection@ttn"
MQTT_API_KEY = "NNSXS.TVDKACYWIP2SSMUPRMOLBUMPNUDOEM6DWKNLEPY.ZD6X2WTQETCCJNNUEHLN7Y4LXGBPOEF3LO2X6R5GVREFQNYYWEDA"
MQTT_PORT = 1883
MQTT_TOPIC = "#"

